apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  name: standard
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
