// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package ecskube

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSContainer) DeepCopyInto(out *ECSContainer) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DNSSearchDomains != nil {
		in, out := &in.DNSSearchDomains, &out.DNSSearchDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DNSServers != nil {
		in, out := &in.DNSServers, &out.DNSServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DockerLabels != nil {
		in, out := &in.DockerLabels, &out.DockerLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make([]ECSKeyValuePair, len(*in))
		copy(*out, *in)
	}
	if in.ExtraHosts != nil {
		in, out := &in.ExtraHosts, &out.ExtraHosts
		*out = make([]ECSHostEntry, len(*in))
		copy(*out, *in)
	}
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LinuxParameters.DeepCopyInto(&out.LinuxParameters)
	in.LogConfiguration.DeepCopyInto(&out.LogConfiguration)
	if in.MountPoints != nil {
		in, out := &in.MountPoints, &out.MountPoints
		*out = make([]ECSMountPoint, len(*in))
		copy(*out, *in)
	}
	if in.PortMappings != nil {
		in, out := &in.PortMappings, &out.PortMappings
		*out = make([]ECSPortMapping, len(*in))
		copy(*out, *in)
	}
	if in.Ulimits != nil {
		in, out := &in.Ulimits, &out.Ulimits
		*out = make([]ECSULimit, len(*in))
		copy(*out, *in)
	}
	if in.VolumesFrom != nil {
		in, out := &in.VolumesFrom, &out.VolumesFrom
		*out = make([]ECSVolumeFrom, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSContainer.
func (in *ECSContainer) DeepCopy() *ECSContainer {
	if in == nil {
		return nil
	}
	out := new(ECSContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSDeployment) DeepCopyInto(out *ECSDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSDeployment.
func (in *ECSDeployment) DeepCopy() *ECSDeployment {
	if in == nil {
		return nil
	}
	out := new(ECSDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ECSDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSDeploymentList) DeepCopyInto(out *ECSDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ECSDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSDeploymentList.
func (in *ECSDeploymentList) DeepCopy() *ECSDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ECSDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ECSDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSDeploymentSpec) DeepCopyInto(out *ECSDeploymentSpec) {
	*out = *in
	in.Task.DeepCopyInto(&out.Task)
	in.Service.DeepCopyInto(&out.Service)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSDeploymentSpec.
func (in *ECSDeploymentSpec) DeepCopy() *ECSDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ECSDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSDeploymentStatus) DeepCopyInto(out *ECSDeploymentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSDeploymentStatus.
func (in *ECSDeploymentStatus) DeepCopy() *ECSDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(ECSDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSDevice) DeepCopyInto(out *ECSDevice) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSDevice.
func (in *ECSDevice) DeepCopy() *ECSDevice {
	if in == nil {
		return nil
	}
	out := new(ECSDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSHostEntry) DeepCopyInto(out *ECSHostEntry) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSHostEntry.
func (in *ECSHostEntry) DeepCopy() *ECSHostEntry {
	if in == nil {
		return nil
	}
	out := new(ECSHostEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSKernelCapabilities) DeepCopyInto(out *ECSKernelCapabilities) {
	*out = *in
	if in.Add != nil {
		in, out := &in.Add, &out.Add
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Drop != nil {
		in, out := &in.Drop, &out.Drop
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSKernelCapabilities.
func (in *ECSKernelCapabilities) DeepCopy() *ECSKernelCapabilities {
	if in == nil {
		return nil
	}
	out := new(ECSKernelCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSKeyValuePair) DeepCopyInto(out *ECSKeyValuePair) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSKeyValuePair.
func (in *ECSKeyValuePair) DeepCopy() *ECSKeyValuePair {
	if in == nil {
		return nil
	}
	out := new(ECSKeyValuePair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSLinuxParameters) DeepCopyInto(out *ECSLinuxParameters) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]ECSKernelCapabilities, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]ECSDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSLinuxParameters.
func (in *ECSLinuxParameters) DeepCopy() *ECSLinuxParameters {
	if in == nil {
		return nil
	}
	out := new(ECSLinuxParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSLoadBalancer) DeepCopyInto(out *ECSLoadBalancer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSLoadBalancer.
func (in *ECSLoadBalancer) DeepCopy() *ECSLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(ECSLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSLogConfiguration) DeepCopyInto(out *ECSLogConfiguration) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSLogConfiguration.
func (in *ECSLogConfiguration) DeepCopy() *ECSLogConfiguration {
	if in == nil {
		return nil
	}
	out := new(ECSLogConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSMountPoint) DeepCopyInto(out *ECSMountPoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSMountPoint.
func (in *ECSMountPoint) DeepCopy() *ECSMountPoint {
	if in == nil {
		return nil
	}
	out := new(ECSMountPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSPlacement) DeepCopyInto(out *ECSPlacement) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSPlacement.
func (in *ECSPlacement) DeepCopy() *ECSPlacement {
	if in == nil {
		return nil
	}
	out := new(ECSPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSPortMapping) DeepCopyInto(out *ECSPortMapping) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSPortMapping.
func (in *ECSPortMapping) DeepCopy() *ECSPortMapping {
	if in == nil {
		return nil
	}
	out := new(ECSPortMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSService) DeepCopyInto(out *ECSService) {
	*out = *in
	if in.LoadBalancers != nil {
		in, out := &in.LoadBalancers, &out.LoadBalancers
		*out = make([]ECSLoadBalancer, len(*in))
		copy(*out, *in)
	}
	out.PlacementConstraints = in.PlacementConstraints
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSService.
func (in *ECSService) DeepCopy() *ECSService {
	if in == nil {
		return nil
	}
	out := new(ECSService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSTask) DeepCopyInto(out *ECSTask) {
	*out = *in
	in.Properties.DeepCopyInto(&out.Properties)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSTask.
func (in *ECSTask) DeepCopy() *ECSTask {
	if in == nil {
		return nil
	}
	out := new(ECSTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSTaskProperties) DeepCopyInto(out *ECSTaskProperties) {
	*out = *in
	out.Volumes = in.Volumes
	out.PlacementConstraints = in.PlacementConstraints
	if in.RequiresCompatibilities != nil {
		in, out := &in.RequiresCompatibilities, &out.RequiresCompatibilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ContainerDefinitions != nil {
		in, out := &in.ContainerDefinitions, &out.ContainerDefinitions
		*out = make([]ECSContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSTaskProperties.
func (in *ECSTaskProperties) DeepCopy() *ECSTaskProperties {
	if in == nil {
		return nil
	}
	out := new(ECSTaskProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSULimit) DeepCopyInto(out *ECSULimit) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSULimit.
func (in *ECSULimit) DeepCopy() *ECSULimit {
	if in == nil {
		return nil
	}
	out := new(ECSULimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSVolumeFrom) DeepCopyInto(out *ECSVolumeFrom) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSVolumeFrom.
func (in *ECSVolumeFrom) DeepCopy() *ECSVolumeFrom {
	if in == nil {
		return nil
	}
	out := new(ECSVolumeFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSVolumeHost) DeepCopyInto(out *ECSVolumeHost) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSVolumeHost.
func (in *ECSVolumeHost) DeepCopy() *ECSVolumeHost {
	if in == nil {
		return nil
	}
	out := new(ECSVolumeHost)
	in.DeepCopyInto(out)
	return out
}
