/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	ecskube_v1alpha1 "github.com/robinpercy/ecs-kube/pkg/apis/ecskube/v1alpha1"
	clientset "github.com/robinpercy/ecs-kube/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/robinpercy/ecs-kube/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/robinpercy/ecs-kube/pkg/client/listers_generated/ecskube/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ECSDeploymentInformer provides access to a shared informer and lister for
// ECSDeployments.
type ECSDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ECSDeploymentLister
}

type eCSDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewECSDeploymentInformer constructs a new informer for ECSDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewECSDeploymentInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredECSDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredECSDeploymentInformer constructs a new informer for ECSDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredECSDeploymentInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EcskubeV1alpha1().ECSDeployments(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EcskubeV1alpha1().ECSDeployments(namespace).Watch(options)
			},
		},
		&ecskube_v1alpha1.ECSDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *eCSDeploymentInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredECSDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *eCSDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ecskube_v1alpha1.ECSDeployment{}, f.defaultInformer)
}

func (f *eCSDeploymentInformer) Lister() v1alpha1.ECSDeploymentLister {
	return v1alpha1.NewECSDeploymentLister(f.Informer().GetIndexer())
}
