// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	ecskube "github.com/robinpercy/ecs-kube/pkg/apis/ecskube"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_ECSContainer_To_ecskube_ECSContainer,
		Convert_ecskube_ECSContainer_To_v1alpha1_ECSContainer,
		Convert_v1alpha1_ECSDeployment_To_ecskube_ECSDeployment,
		Convert_ecskube_ECSDeployment_To_v1alpha1_ECSDeployment,
		Convert_v1alpha1_ECSDeploymentList_To_ecskube_ECSDeploymentList,
		Convert_ecskube_ECSDeploymentList_To_v1alpha1_ECSDeploymentList,
		Convert_v1alpha1_ECSDeploymentSpec_To_ecskube_ECSDeploymentSpec,
		Convert_ecskube_ECSDeploymentSpec_To_v1alpha1_ECSDeploymentSpec,
		Convert_v1alpha1_ECSDeploymentStatus_To_ecskube_ECSDeploymentStatus,
		Convert_ecskube_ECSDeploymentStatus_To_v1alpha1_ECSDeploymentStatus,
		Convert_v1alpha1_ECSDeploymentStatusStrategy_To_ecskube_ECSDeploymentStatusStrategy,
		Convert_ecskube_ECSDeploymentStatusStrategy_To_v1alpha1_ECSDeploymentStatusStrategy,
		Convert_v1alpha1_ECSDeploymentStrategy_To_ecskube_ECSDeploymentStrategy,
		Convert_ecskube_ECSDeploymentStrategy_To_v1alpha1_ECSDeploymentStrategy,
		Convert_v1alpha1_ECSDevice_To_ecskube_ECSDevice,
		Convert_ecskube_ECSDevice_To_v1alpha1_ECSDevice,
		Convert_v1alpha1_ECSHostEntry_To_ecskube_ECSHostEntry,
		Convert_ecskube_ECSHostEntry_To_v1alpha1_ECSHostEntry,
		Convert_v1alpha1_ECSKernelCapabilities_To_ecskube_ECSKernelCapabilities,
		Convert_ecskube_ECSKernelCapabilities_To_v1alpha1_ECSKernelCapabilities,
		Convert_v1alpha1_ECSKeyValuePair_To_ecskube_ECSKeyValuePair,
		Convert_ecskube_ECSKeyValuePair_To_v1alpha1_ECSKeyValuePair,
		Convert_v1alpha1_ECSLinuxParameters_To_ecskube_ECSLinuxParameters,
		Convert_ecskube_ECSLinuxParameters_To_v1alpha1_ECSLinuxParameters,
		Convert_v1alpha1_ECSLoadBalancer_To_ecskube_ECSLoadBalancer,
		Convert_ecskube_ECSLoadBalancer_To_v1alpha1_ECSLoadBalancer,
		Convert_v1alpha1_ECSLogConfiguration_To_ecskube_ECSLogConfiguration,
		Convert_ecskube_ECSLogConfiguration_To_v1alpha1_ECSLogConfiguration,
		Convert_v1alpha1_ECSMountPoint_To_ecskube_ECSMountPoint,
		Convert_ecskube_ECSMountPoint_To_v1alpha1_ECSMountPoint,
		Convert_v1alpha1_ECSPlacement_To_ecskube_ECSPlacement,
		Convert_ecskube_ECSPlacement_To_v1alpha1_ECSPlacement,
		Convert_v1alpha1_ECSPortMapping_To_ecskube_ECSPortMapping,
		Convert_ecskube_ECSPortMapping_To_v1alpha1_ECSPortMapping,
		Convert_v1alpha1_ECSService_To_ecskube_ECSService,
		Convert_ecskube_ECSService_To_v1alpha1_ECSService,
		Convert_v1alpha1_ECSTask_To_ecskube_ECSTask,
		Convert_ecskube_ECSTask_To_v1alpha1_ECSTask,
		Convert_v1alpha1_ECSTaskProperties_To_ecskube_ECSTaskProperties,
		Convert_ecskube_ECSTaskProperties_To_v1alpha1_ECSTaskProperties,
		Convert_v1alpha1_ECSULimit_To_ecskube_ECSULimit,
		Convert_ecskube_ECSULimit_To_v1alpha1_ECSULimit,
		Convert_v1alpha1_ECSVolumeFrom_To_ecskube_ECSVolumeFrom,
		Convert_ecskube_ECSVolumeFrom_To_v1alpha1_ECSVolumeFrom,
		Convert_v1alpha1_ECSVolumeHost_To_ecskube_ECSVolumeHost,
		Convert_ecskube_ECSVolumeHost_To_v1alpha1_ECSVolumeHost,
	)
}

func autoConvert_v1alpha1_ECSContainer_To_ecskube_ECSContainer(in *ECSContainer, out *ecskube.ECSContainer, s conversion.Scope) error {
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.CPU = in.CPU
	out.DisableNetworking = in.DisableNetworking
	out.DNSSearchDomains = *(*[]string)(unsafe.Pointer(&in.DNSSearchDomains))
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	out.DockerLabels = *(*map[string]string)(unsafe.Pointer(&in.DockerLabels))
	out.DockerSecurityOptions = in.DockerSecurityOptions
	out.EntryPoint = in.EntryPoint
	out.Environment = *(*[]ecskube.ECSKeyValuePair)(unsafe.Pointer(&in.Environment))
	out.Essential = in.Essential
	out.ExtraHosts = *(*[]ecskube.ECSHostEntry)(unsafe.Pointer(&in.ExtraHosts))
	out.Hostname = in.Hostname
	out.Image = in.Image
	out.Links = *(*[]string)(unsafe.Pointer(&in.Links))
	if err := Convert_v1alpha1_ECSLinuxParameters_To_ecskube_ECSLinuxParameters(&in.LinuxParameters, &out.LinuxParameters, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ECSLogConfiguration_To_ecskube_ECSLogConfiguration(&in.LogConfiguration, &out.LogConfiguration, s); err != nil {
		return err
	}
	out.Memory = in.Memory
	out.MemoryReservation = in.MemoryReservation
	out.MountPoints = *(*[]ecskube.ECSMountPoint)(unsafe.Pointer(&in.MountPoints))
	out.Name = in.Name
	out.PortMappings = *(*[]ecskube.ECSPortMapping)(unsafe.Pointer(&in.PortMappings))
	out.Privileged = in.Privileged
	out.ReadonlyRootFilesystem = in.ReadonlyRootFilesystem
	out.Ulimits = *(*[]ecskube.ECSULimit)(unsafe.Pointer(&in.Ulimits))
	out.User = in.User
	out.VolumesFrom = *(*[]ecskube.ECSVolumeFrom)(unsafe.Pointer(&in.VolumesFrom))
	out.WorkingDirectory = in.WorkingDirectory
	return nil
}

// Convert_v1alpha1_ECSContainer_To_ecskube_ECSContainer is an autogenerated conversion function.
func Convert_v1alpha1_ECSContainer_To_ecskube_ECSContainer(in *ECSContainer, out *ecskube.ECSContainer, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSContainer_To_ecskube_ECSContainer(in, out, s)
}

func autoConvert_ecskube_ECSContainer_To_v1alpha1_ECSContainer(in *ecskube.ECSContainer, out *ECSContainer, s conversion.Scope) error {
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.CPU = in.CPU
	out.DisableNetworking = in.DisableNetworking
	out.DNSSearchDomains = *(*[]string)(unsafe.Pointer(&in.DNSSearchDomains))
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	out.DockerLabels = *(*map[string]string)(unsafe.Pointer(&in.DockerLabels))
	out.DockerSecurityOptions = in.DockerSecurityOptions
	out.EntryPoint = in.EntryPoint
	out.Environment = *(*[]ECSKeyValuePair)(unsafe.Pointer(&in.Environment))
	out.Essential = in.Essential
	out.ExtraHosts = *(*[]ECSHostEntry)(unsafe.Pointer(&in.ExtraHosts))
	out.Hostname = in.Hostname
	out.Image = in.Image
	out.Links = *(*[]string)(unsafe.Pointer(&in.Links))
	if err := Convert_ecskube_ECSLinuxParameters_To_v1alpha1_ECSLinuxParameters(&in.LinuxParameters, &out.LinuxParameters, s); err != nil {
		return err
	}
	if err := Convert_ecskube_ECSLogConfiguration_To_v1alpha1_ECSLogConfiguration(&in.LogConfiguration, &out.LogConfiguration, s); err != nil {
		return err
	}
	out.Memory = in.Memory
	out.MemoryReservation = in.MemoryReservation
	out.MountPoints = *(*[]ECSMountPoint)(unsafe.Pointer(&in.MountPoints))
	out.Name = in.Name
	out.PortMappings = *(*[]ECSPortMapping)(unsafe.Pointer(&in.PortMappings))
	out.Privileged = in.Privileged
	out.ReadonlyRootFilesystem = in.ReadonlyRootFilesystem
	out.Ulimits = *(*[]ECSULimit)(unsafe.Pointer(&in.Ulimits))
	out.User = in.User
	out.VolumesFrom = *(*[]ECSVolumeFrom)(unsafe.Pointer(&in.VolumesFrom))
	out.WorkingDirectory = in.WorkingDirectory
	return nil
}

// Convert_ecskube_ECSContainer_To_v1alpha1_ECSContainer is an autogenerated conversion function.
func Convert_ecskube_ECSContainer_To_v1alpha1_ECSContainer(in *ecskube.ECSContainer, out *ECSContainer, s conversion.Scope) error {
	return autoConvert_ecskube_ECSContainer_To_v1alpha1_ECSContainer(in, out, s)
}

func autoConvert_v1alpha1_ECSDeployment_To_ecskube_ECSDeployment(in *ECSDeployment, out *ecskube.ECSDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ECSDeploymentSpec_To_ecskube_ECSDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ECSDeploymentStatus_To_ecskube_ECSDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ECSDeployment_To_ecskube_ECSDeployment is an autogenerated conversion function.
func Convert_v1alpha1_ECSDeployment_To_ecskube_ECSDeployment(in *ECSDeployment, out *ecskube.ECSDeployment, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSDeployment_To_ecskube_ECSDeployment(in, out, s)
}

func autoConvert_ecskube_ECSDeployment_To_v1alpha1_ECSDeployment(in *ecskube.ECSDeployment, out *ECSDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_ecskube_ECSDeploymentSpec_To_v1alpha1_ECSDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_ecskube_ECSDeploymentStatus_To_v1alpha1_ECSDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_ecskube_ECSDeployment_To_v1alpha1_ECSDeployment is an autogenerated conversion function.
func Convert_ecskube_ECSDeployment_To_v1alpha1_ECSDeployment(in *ecskube.ECSDeployment, out *ECSDeployment, s conversion.Scope) error {
	return autoConvert_ecskube_ECSDeployment_To_v1alpha1_ECSDeployment(in, out, s)
}

func autoConvert_v1alpha1_ECSDeploymentList_To_ecskube_ECSDeploymentList(in *ECSDeploymentList, out *ecskube.ECSDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ecskube.ECSDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ECSDeploymentList_To_ecskube_ECSDeploymentList is an autogenerated conversion function.
func Convert_v1alpha1_ECSDeploymentList_To_ecskube_ECSDeploymentList(in *ECSDeploymentList, out *ecskube.ECSDeploymentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSDeploymentList_To_ecskube_ECSDeploymentList(in, out, s)
}

func autoConvert_ecskube_ECSDeploymentList_To_v1alpha1_ECSDeploymentList(in *ecskube.ECSDeploymentList, out *ECSDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ECSDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_ecskube_ECSDeploymentList_To_v1alpha1_ECSDeploymentList is an autogenerated conversion function.
func Convert_ecskube_ECSDeploymentList_To_v1alpha1_ECSDeploymentList(in *ecskube.ECSDeploymentList, out *ECSDeploymentList, s conversion.Scope) error {
	return autoConvert_ecskube_ECSDeploymentList_To_v1alpha1_ECSDeploymentList(in, out, s)
}

func autoConvert_v1alpha1_ECSDeploymentSpec_To_ecskube_ECSDeploymentSpec(in *ECSDeploymentSpec, out *ecskube.ECSDeploymentSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ECSTask_To_ecskube_ECSTask(&in.Task, &out.Task, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ECSService_To_ecskube_ECSService(&in.Service, &out.Service, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ECSDeploymentSpec_To_ecskube_ECSDeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha1_ECSDeploymentSpec_To_ecskube_ECSDeploymentSpec(in *ECSDeploymentSpec, out *ecskube.ECSDeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSDeploymentSpec_To_ecskube_ECSDeploymentSpec(in, out, s)
}

func autoConvert_ecskube_ECSDeploymentSpec_To_v1alpha1_ECSDeploymentSpec(in *ecskube.ECSDeploymentSpec, out *ECSDeploymentSpec, s conversion.Scope) error {
	if err := Convert_ecskube_ECSTask_To_v1alpha1_ECSTask(&in.Task, &out.Task, s); err != nil {
		return err
	}
	if err := Convert_ecskube_ECSService_To_v1alpha1_ECSService(&in.Service, &out.Service, s); err != nil {
		return err
	}
	return nil
}

// Convert_ecskube_ECSDeploymentSpec_To_v1alpha1_ECSDeploymentSpec is an autogenerated conversion function.
func Convert_ecskube_ECSDeploymentSpec_To_v1alpha1_ECSDeploymentSpec(in *ecskube.ECSDeploymentSpec, out *ECSDeploymentSpec, s conversion.Scope) error {
	return autoConvert_ecskube_ECSDeploymentSpec_To_v1alpha1_ECSDeploymentSpec(in, out, s)
}

func autoConvert_v1alpha1_ECSDeploymentStatus_To_ecskube_ECSDeploymentStatus(in *ECSDeploymentStatus, out *ecskube.ECSDeploymentStatus, s conversion.Scope) error {
	out.State = in.State
	return nil
}

// Convert_v1alpha1_ECSDeploymentStatus_To_ecskube_ECSDeploymentStatus is an autogenerated conversion function.
func Convert_v1alpha1_ECSDeploymentStatus_To_ecskube_ECSDeploymentStatus(in *ECSDeploymentStatus, out *ecskube.ECSDeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSDeploymentStatus_To_ecskube_ECSDeploymentStatus(in, out, s)
}

func autoConvert_ecskube_ECSDeploymentStatus_To_v1alpha1_ECSDeploymentStatus(in *ecskube.ECSDeploymentStatus, out *ECSDeploymentStatus, s conversion.Scope) error {
	out.State = in.State
	return nil
}

// Convert_ecskube_ECSDeploymentStatus_To_v1alpha1_ECSDeploymentStatus is an autogenerated conversion function.
func Convert_ecskube_ECSDeploymentStatus_To_v1alpha1_ECSDeploymentStatus(in *ecskube.ECSDeploymentStatus, out *ECSDeploymentStatus, s conversion.Scope) error {
	return autoConvert_ecskube_ECSDeploymentStatus_To_v1alpha1_ECSDeploymentStatus(in, out, s)
}

func autoConvert_v1alpha1_ECSDeploymentStatusStrategy_To_ecskube_ECSDeploymentStatusStrategy(in *ECSDeploymentStatusStrategy, out *ecskube.ECSDeploymentStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_ECSDeploymentStatusStrategy_To_ecskube_ECSDeploymentStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_ECSDeploymentStatusStrategy_To_ecskube_ECSDeploymentStatusStrategy(in *ECSDeploymentStatusStrategy, out *ecskube.ECSDeploymentStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSDeploymentStatusStrategy_To_ecskube_ECSDeploymentStatusStrategy(in, out, s)
}

func autoConvert_ecskube_ECSDeploymentStatusStrategy_To_v1alpha1_ECSDeploymentStatusStrategy(in *ecskube.ECSDeploymentStatusStrategy, out *ECSDeploymentStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_ecskube_ECSDeploymentStatusStrategy_To_v1alpha1_ECSDeploymentStatusStrategy is an autogenerated conversion function.
func Convert_ecskube_ECSDeploymentStatusStrategy_To_v1alpha1_ECSDeploymentStatusStrategy(in *ecskube.ECSDeploymentStatusStrategy, out *ECSDeploymentStatusStrategy, s conversion.Scope) error {
	return autoConvert_ecskube_ECSDeploymentStatusStrategy_To_v1alpha1_ECSDeploymentStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_ECSDeploymentStrategy_To_ecskube_ECSDeploymentStrategy(in *ECSDeploymentStrategy, out *ecskube.ECSDeploymentStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_ECSDeploymentStrategy_To_ecskube_ECSDeploymentStrategy is an autogenerated conversion function.
func Convert_v1alpha1_ECSDeploymentStrategy_To_ecskube_ECSDeploymentStrategy(in *ECSDeploymentStrategy, out *ecskube.ECSDeploymentStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSDeploymentStrategy_To_ecskube_ECSDeploymentStrategy(in, out, s)
}

func autoConvert_ecskube_ECSDeploymentStrategy_To_v1alpha1_ECSDeploymentStrategy(in *ecskube.ECSDeploymentStrategy, out *ECSDeploymentStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_ecskube_ECSDeploymentStrategy_To_v1alpha1_ECSDeploymentStrategy is an autogenerated conversion function.
func Convert_ecskube_ECSDeploymentStrategy_To_v1alpha1_ECSDeploymentStrategy(in *ecskube.ECSDeploymentStrategy, out *ECSDeploymentStrategy, s conversion.Scope) error {
	return autoConvert_ecskube_ECSDeploymentStrategy_To_v1alpha1_ECSDeploymentStrategy(in, out, s)
}

func autoConvert_v1alpha1_ECSDevice_To_ecskube_ECSDevice(in *ECSDevice, out *ecskube.ECSDevice, s conversion.Scope) error {
	out.ContainerPath = in.ContainerPath
	out.HostPath = in.HostPath
	out.Permissions = *(*[]string)(unsafe.Pointer(&in.Permissions))
	return nil
}

// Convert_v1alpha1_ECSDevice_To_ecskube_ECSDevice is an autogenerated conversion function.
func Convert_v1alpha1_ECSDevice_To_ecskube_ECSDevice(in *ECSDevice, out *ecskube.ECSDevice, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSDevice_To_ecskube_ECSDevice(in, out, s)
}

func autoConvert_ecskube_ECSDevice_To_v1alpha1_ECSDevice(in *ecskube.ECSDevice, out *ECSDevice, s conversion.Scope) error {
	out.ContainerPath = in.ContainerPath
	out.HostPath = in.HostPath
	out.Permissions = *(*[]string)(unsafe.Pointer(&in.Permissions))
	return nil
}

// Convert_ecskube_ECSDevice_To_v1alpha1_ECSDevice is an autogenerated conversion function.
func Convert_ecskube_ECSDevice_To_v1alpha1_ECSDevice(in *ecskube.ECSDevice, out *ECSDevice, s conversion.Scope) error {
	return autoConvert_ecskube_ECSDevice_To_v1alpha1_ECSDevice(in, out, s)
}

func autoConvert_v1alpha1_ECSHostEntry_To_ecskube_ECSHostEntry(in *ECSHostEntry, out *ecskube.ECSHostEntry, s conversion.Scope) error {
	out.Hostname = in.Hostname
	out.IPAddress = in.IPAddress
	return nil
}

// Convert_v1alpha1_ECSHostEntry_To_ecskube_ECSHostEntry is an autogenerated conversion function.
func Convert_v1alpha1_ECSHostEntry_To_ecskube_ECSHostEntry(in *ECSHostEntry, out *ecskube.ECSHostEntry, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSHostEntry_To_ecskube_ECSHostEntry(in, out, s)
}

func autoConvert_ecskube_ECSHostEntry_To_v1alpha1_ECSHostEntry(in *ecskube.ECSHostEntry, out *ECSHostEntry, s conversion.Scope) error {
	out.Hostname = in.Hostname
	out.IPAddress = in.IPAddress
	return nil
}

// Convert_ecskube_ECSHostEntry_To_v1alpha1_ECSHostEntry is an autogenerated conversion function.
func Convert_ecskube_ECSHostEntry_To_v1alpha1_ECSHostEntry(in *ecskube.ECSHostEntry, out *ECSHostEntry, s conversion.Scope) error {
	return autoConvert_ecskube_ECSHostEntry_To_v1alpha1_ECSHostEntry(in, out, s)
}

func autoConvert_v1alpha1_ECSKernelCapabilities_To_ecskube_ECSKernelCapabilities(in *ECSKernelCapabilities, out *ecskube.ECSKernelCapabilities, s conversion.Scope) error {
	out.Add = *(*[]string)(unsafe.Pointer(&in.Add))
	out.Drop = *(*[]string)(unsafe.Pointer(&in.Drop))
	return nil
}

// Convert_v1alpha1_ECSKernelCapabilities_To_ecskube_ECSKernelCapabilities is an autogenerated conversion function.
func Convert_v1alpha1_ECSKernelCapabilities_To_ecskube_ECSKernelCapabilities(in *ECSKernelCapabilities, out *ecskube.ECSKernelCapabilities, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSKernelCapabilities_To_ecskube_ECSKernelCapabilities(in, out, s)
}

func autoConvert_ecskube_ECSKernelCapabilities_To_v1alpha1_ECSKernelCapabilities(in *ecskube.ECSKernelCapabilities, out *ECSKernelCapabilities, s conversion.Scope) error {
	out.Add = *(*[]string)(unsafe.Pointer(&in.Add))
	out.Drop = *(*[]string)(unsafe.Pointer(&in.Drop))
	return nil
}

// Convert_ecskube_ECSKernelCapabilities_To_v1alpha1_ECSKernelCapabilities is an autogenerated conversion function.
func Convert_ecskube_ECSKernelCapabilities_To_v1alpha1_ECSKernelCapabilities(in *ecskube.ECSKernelCapabilities, out *ECSKernelCapabilities, s conversion.Scope) error {
	return autoConvert_ecskube_ECSKernelCapabilities_To_v1alpha1_ECSKernelCapabilities(in, out, s)
}

func autoConvert_v1alpha1_ECSKeyValuePair_To_ecskube_ECSKeyValuePair(in *ECSKeyValuePair, out *ecskube.ECSKeyValuePair, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_ECSKeyValuePair_To_ecskube_ECSKeyValuePair is an autogenerated conversion function.
func Convert_v1alpha1_ECSKeyValuePair_To_ecskube_ECSKeyValuePair(in *ECSKeyValuePair, out *ecskube.ECSKeyValuePair, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSKeyValuePair_To_ecskube_ECSKeyValuePair(in, out, s)
}

func autoConvert_ecskube_ECSKeyValuePair_To_v1alpha1_ECSKeyValuePair(in *ecskube.ECSKeyValuePair, out *ECSKeyValuePair, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_ecskube_ECSKeyValuePair_To_v1alpha1_ECSKeyValuePair is an autogenerated conversion function.
func Convert_ecskube_ECSKeyValuePair_To_v1alpha1_ECSKeyValuePair(in *ecskube.ECSKeyValuePair, out *ECSKeyValuePair, s conversion.Scope) error {
	return autoConvert_ecskube_ECSKeyValuePair_To_v1alpha1_ECSKeyValuePair(in, out, s)
}

func autoConvert_v1alpha1_ECSLinuxParameters_To_ecskube_ECSLinuxParameters(in *ECSLinuxParameters, out *ecskube.ECSLinuxParameters, s conversion.Scope) error {
	out.Capabilities = *(*[]ecskube.ECSKernelCapabilities)(unsafe.Pointer(&in.Capabilities))
	out.Devices = *(*[]ecskube.ECSDevice)(unsafe.Pointer(&in.Devices))
	out.InitProcessEnabled = in.InitProcessEnabled
	return nil
}

// Convert_v1alpha1_ECSLinuxParameters_To_ecskube_ECSLinuxParameters is an autogenerated conversion function.
func Convert_v1alpha1_ECSLinuxParameters_To_ecskube_ECSLinuxParameters(in *ECSLinuxParameters, out *ecskube.ECSLinuxParameters, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSLinuxParameters_To_ecskube_ECSLinuxParameters(in, out, s)
}

func autoConvert_ecskube_ECSLinuxParameters_To_v1alpha1_ECSLinuxParameters(in *ecskube.ECSLinuxParameters, out *ECSLinuxParameters, s conversion.Scope) error {
	out.Capabilities = *(*[]ECSKernelCapabilities)(unsafe.Pointer(&in.Capabilities))
	out.Devices = *(*[]ECSDevice)(unsafe.Pointer(&in.Devices))
	out.InitProcessEnabled = in.InitProcessEnabled
	return nil
}

// Convert_ecskube_ECSLinuxParameters_To_v1alpha1_ECSLinuxParameters is an autogenerated conversion function.
func Convert_ecskube_ECSLinuxParameters_To_v1alpha1_ECSLinuxParameters(in *ecskube.ECSLinuxParameters, out *ECSLinuxParameters, s conversion.Scope) error {
	return autoConvert_ecskube_ECSLinuxParameters_To_v1alpha1_ECSLinuxParameters(in, out, s)
}

func autoConvert_v1alpha1_ECSLoadBalancer_To_ecskube_ECSLoadBalancer(in *ECSLoadBalancer, out *ecskube.ECSLoadBalancer, s conversion.Scope) error {
	out.ContainerName = in.ContainerName
	out.ContainerPort = in.ContainerPort
	out.LoadBalancerName = in.LoadBalancerName
	out.TargetGroupArn = in.TargetGroupArn
	return nil
}

// Convert_v1alpha1_ECSLoadBalancer_To_ecskube_ECSLoadBalancer is an autogenerated conversion function.
func Convert_v1alpha1_ECSLoadBalancer_To_ecskube_ECSLoadBalancer(in *ECSLoadBalancer, out *ecskube.ECSLoadBalancer, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSLoadBalancer_To_ecskube_ECSLoadBalancer(in, out, s)
}

func autoConvert_ecskube_ECSLoadBalancer_To_v1alpha1_ECSLoadBalancer(in *ecskube.ECSLoadBalancer, out *ECSLoadBalancer, s conversion.Scope) error {
	out.ContainerName = in.ContainerName
	out.ContainerPort = in.ContainerPort
	out.LoadBalancerName = in.LoadBalancerName
	out.TargetGroupArn = in.TargetGroupArn
	return nil
}

// Convert_ecskube_ECSLoadBalancer_To_v1alpha1_ECSLoadBalancer is an autogenerated conversion function.
func Convert_ecskube_ECSLoadBalancer_To_v1alpha1_ECSLoadBalancer(in *ecskube.ECSLoadBalancer, out *ECSLoadBalancer, s conversion.Scope) error {
	return autoConvert_ecskube_ECSLoadBalancer_To_v1alpha1_ECSLoadBalancer(in, out, s)
}

func autoConvert_v1alpha1_ECSLogConfiguration_To_ecskube_ECSLogConfiguration(in *ECSLogConfiguration, out *ecskube.ECSLogConfiguration, s conversion.Scope) error {
	out.LogDriver = in.LogDriver
	out.Options = *(*map[string]string)(unsafe.Pointer(&in.Options))
	return nil
}

// Convert_v1alpha1_ECSLogConfiguration_To_ecskube_ECSLogConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ECSLogConfiguration_To_ecskube_ECSLogConfiguration(in *ECSLogConfiguration, out *ecskube.ECSLogConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSLogConfiguration_To_ecskube_ECSLogConfiguration(in, out, s)
}

func autoConvert_ecskube_ECSLogConfiguration_To_v1alpha1_ECSLogConfiguration(in *ecskube.ECSLogConfiguration, out *ECSLogConfiguration, s conversion.Scope) error {
	out.LogDriver = in.LogDriver
	out.Options = *(*map[string]string)(unsafe.Pointer(&in.Options))
	return nil
}

// Convert_ecskube_ECSLogConfiguration_To_v1alpha1_ECSLogConfiguration is an autogenerated conversion function.
func Convert_ecskube_ECSLogConfiguration_To_v1alpha1_ECSLogConfiguration(in *ecskube.ECSLogConfiguration, out *ECSLogConfiguration, s conversion.Scope) error {
	return autoConvert_ecskube_ECSLogConfiguration_To_v1alpha1_ECSLogConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ECSMountPoint_To_ecskube_ECSMountPoint(in *ECSMountPoint, out *ecskube.ECSMountPoint, s conversion.Scope) error {
	out.ContainerPath = in.ContainerPath
	out.SourceVolume = in.SourceVolume
	out.ReadOnly = in.ReadOnly
	return nil
}

// Convert_v1alpha1_ECSMountPoint_To_ecskube_ECSMountPoint is an autogenerated conversion function.
func Convert_v1alpha1_ECSMountPoint_To_ecskube_ECSMountPoint(in *ECSMountPoint, out *ecskube.ECSMountPoint, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSMountPoint_To_ecskube_ECSMountPoint(in, out, s)
}

func autoConvert_ecskube_ECSMountPoint_To_v1alpha1_ECSMountPoint(in *ecskube.ECSMountPoint, out *ECSMountPoint, s conversion.Scope) error {
	out.ContainerPath = in.ContainerPath
	out.SourceVolume = in.SourceVolume
	out.ReadOnly = in.ReadOnly
	return nil
}

// Convert_ecskube_ECSMountPoint_To_v1alpha1_ECSMountPoint is an autogenerated conversion function.
func Convert_ecskube_ECSMountPoint_To_v1alpha1_ECSMountPoint(in *ecskube.ECSMountPoint, out *ECSMountPoint, s conversion.Scope) error {
	return autoConvert_ecskube_ECSMountPoint_To_v1alpha1_ECSMountPoint(in, out, s)
}

func autoConvert_v1alpha1_ECSPlacement_To_ecskube_ECSPlacement(in *ECSPlacement, out *ecskube.ECSPlacement, s conversion.Scope) error {
	out.Type = in.Type
	out.Expression = in.Expression
	return nil
}

// Convert_v1alpha1_ECSPlacement_To_ecskube_ECSPlacement is an autogenerated conversion function.
func Convert_v1alpha1_ECSPlacement_To_ecskube_ECSPlacement(in *ECSPlacement, out *ecskube.ECSPlacement, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSPlacement_To_ecskube_ECSPlacement(in, out, s)
}

func autoConvert_ecskube_ECSPlacement_To_v1alpha1_ECSPlacement(in *ecskube.ECSPlacement, out *ECSPlacement, s conversion.Scope) error {
	out.Type = in.Type
	out.Expression = in.Expression
	return nil
}

// Convert_ecskube_ECSPlacement_To_v1alpha1_ECSPlacement is an autogenerated conversion function.
func Convert_ecskube_ECSPlacement_To_v1alpha1_ECSPlacement(in *ecskube.ECSPlacement, out *ECSPlacement, s conversion.Scope) error {
	return autoConvert_ecskube_ECSPlacement_To_v1alpha1_ECSPlacement(in, out, s)
}

func autoConvert_v1alpha1_ECSPortMapping_To_ecskube_ECSPortMapping(in *ECSPortMapping, out *ecskube.ECSPortMapping, s conversion.Scope) error {
	out.ContainerPort = in.ContainerPort
	out.HostPort = in.HostPort
	out.Protocol = in.Protocol
	return nil
}

// Convert_v1alpha1_ECSPortMapping_To_ecskube_ECSPortMapping is an autogenerated conversion function.
func Convert_v1alpha1_ECSPortMapping_To_ecskube_ECSPortMapping(in *ECSPortMapping, out *ecskube.ECSPortMapping, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSPortMapping_To_ecskube_ECSPortMapping(in, out, s)
}

func autoConvert_ecskube_ECSPortMapping_To_v1alpha1_ECSPortMapping(in *ecskube.ECSPortMapping, out *ECSPortMapping, s conversion.Scope) error {
	out.ContainerPort = in.ContainerPort
	out.HostPort = in.HostPort
	out.Protocol = in.Protocol
	return nil
}

// Convert_ecskube_ECSPortMapping_To_v1alpha1_ECSPortMapping is an autogenerated conversion function.
func Convert_ecskube_ECSPortMapping_To_v1alpha1_ECSPortMapping(in *ecskube.ECSPortMapping, out *ECSPortMapping, s conversion.Scope) error {
	return autoConvert_ecskube_ECSPortMapping_To_v1alpha1_ECSPortMapping(in, out, s)
}

func autoConvert_v1alpha1_ECSService_To_ecskube_ECSService(in *ECSService, out *ecskube.ECSService, s conversion.Scope) error {
	out.Cluster = in.Cluster
	out.DesiredCount = in.DesiredCount
	out.HealthCheckGracePeriodSeconds = in.HealthCheckGracePeriodSeconds
	out.LaunchType = in.LaunchType
	out.LoadBalancers = *(*[]ecskube.ECSLoadBalancer)(unsafe.Pointer(&in.LoadBalancers))
	if err := Convert_v1alpha1_ECSPlacement_To_ecskube_ECSPlacement(&in.PlacementConstraints, &out.PlacementConstraints, s); err != nil {
		return err
	}
	out.PlatformVersion = in.PlatformVersion
	out.Role = in.Role
	out.ServiceName = in.ServiceName
	out.TaskDefinition = in.TaskDefinition
	return nil
}

// Convert_v1alpha1_ECSService_To_ecskube_ECSService is an autogenerated conversion function.
func Convert_v1alpha1_ECSService_To_ecskube_ECSService(in *ECSService, out *ecskube.ECSService, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSService_To_ecskube_ECSService(in, out, s)
}

func autoConvert_ecskube_ECSService_To_v1alpha1_ECSService(in *ecskube.ECSService, out *ECSService, s conversion.Scope) error {
	out.Cluster = in.Cluster
	out.DesiredCount = in.DesiredCount
	out.HealthCheckGracePeriodSeconds = in.HealthCheckGracePeriodSeconds
	out.LaunchType = in.LaunchType
	out.LoadBalancers = *(*[]ECSLoadBalancer)(unsafe.Pointer(&in.LoadBalancers))
	if err := Convert_ecskube_ECSPlacement_To_v1alpha1_ECSPlacement(&in.PlacementConstraints, &out.PlacementConstraints, s); err != nil {
		return err
	}
	out.PlatformVersion = in.PlatformVersion
	out.Role = in.Role
	out.ServiceName = in.ServiceName
	out.TaskDefinition = in.TaskDefinition
	return nil
}

// Convert_ecskube_ECSService_To_v1alpha1_ECSService is an autogenerated conversion function.
func Convert_ecskube_ECSService_To_v1alpha1_ECSService(in *ecskube.ECSService, out *ECSService, s conversion.Scope) error {
	return autoConvert_ecskube_ECSService_To_v1alpha1_ECSService(in, out, s)
}

func autoConvert_v1alpha1_ECSTask_To_ecskube_ECSTask(in *ECSTask, out *ecskube.ECSTask, s conversion.Scope) error {
	out.Type = in.Type
	if err := Convert_v1alpha1_ECSTaskProperties_To_ecskube_ECSTaskProperties(&in.Properties, &out.Properties, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ECSTask_To_ecskube_ECSTask is an autogenerated conversion function.
func Convert_v1alpha1_ECSTask_To_ecskube_ECSTask(in *ECSTask, out *ecskube.ECSTask, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSTask_To_ecskube_ECSTask(in, out, s)
}

func autoConvert_ecskube_ECSTask_To_v1alpha1_ECSTask(in *ecskube.ECSTask, out *ECSTask, s conversion.Scope) error {
	out.Type = in.Type
	if err := Convert_ecskube_ECSTaskProperties_To_v1alpha1_ECSTaskProperties(&in.Properties, &out.Properties, s); err != nil {
		return err
	}
	return nil
}

// Convert_ecskube_ECSTask_To_v1alpha1_ECSTask is an autogenerated conversion function.
func Convert_ecskube_ECSTask_To_v1alpha1_ECSTask(in *ecskube.ECSTask, out *ECSTask, s conversion.Scope) error {
	return autoConvert_ecskube_ECSTask_To_v1alpha1_ECSTask(in, out, s)
}

func autoConvert_v1alpha1_ECSTaskProperties_To_ecskube_ECSTaskProperties(in *ECSTaskProperties, out *ecskube.ECSTaskProperties, s conversion.Scope) error {
	if err := Convert_v1alpha1_ECSVolumeHost_To_ecskube_ECSVolumeHost(&in.Volumes, &out.Volumes, s); err != nil {
		return err
	}
	out.CPU = in.CPU
	out.ExecutionRoleARN = in.ExecutionRoleARN
	out.Family = in.Family
	out.Memory = in.Memory
	out.NetworkMode = in.NetworkMode
	if err := Convert_v1alpha1_ECSPlacement_To_ecskube_ECSPlacement(&in.PlacementConstraints, &out.PlacementConstraints, s); err != nil {
		return err
	}
	out.RequiresCompatibilities = *(*[]string)(unsafe.Pointer(&in.RequiresCompatibilities))
	out.TaskRoleARN = in.TaskRoleARN
	out.ContainerDefinitions = *(*[]ecskube.ECSContainer)(unsafe.Pointer(&in.ContainerDefinitions))
	return nil
}

// Convert_v1alpha1_ECSTaskProperties_To_ecskube_ECSTaskProperties is an autogenerated conversion function.
func Convert_v1alpha1_ECSTaskProperties_To_ecskube_ECSTaskProperties(in *ECSTaskProperties, out *ecskube.ECSTaskProperties, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSTaskProperties_To_ecskube_ECSTaskProperties(in, out, s)
}

func autoConvert_ecskube_ECSTaskProperties_To_v1alpha1_ECSTaskProperties(in *ecskube.ECSTaskProperties, out *ECSTaskProperties, s conversion.Scope) error {
	if err := Convert_ecskube_ECSVolumeHost_To_v1alpha1_ECSVolumeHost(&in.Volumes, &out.Volumes, s); err != nil {
		return err
	}
	out.CPU = in.CPU
	out.ExecutionRoleARN = in.ExecutionRoleARN
	out.Family = in.Family
	out.Memory = in.Memory
	out.NetworkMode = in.NetworkMode
	if err := Convert_ecskube_ECSPlacement_To_v1alpha1_ECSPlacement(&in.PlacementConstraints, &out.PlacementConstraints, s); err != nil {
		return err
	}
	out.RequiresCompatibilities = *(*[]string)(unsafe.Pointer(&in.RequiresCompatibilities))
	out.TaskRoleARN = in.TaskRoleARN
	out.ContainerDefinitions = *(*[]ECSContainer)(unsafe.Pointer(&in.ContainerDefinitions))
	return nil
}

// Convert_ecskube_ECSTaskProperties_To_v1alpha1_ECSTaskProperties is an autogenerated conversion function.
func Convert_ecskube_ECSTaskProperties_To_v1alpha1_ECSTaskProperties(in *ecskube.ECSTaskProperties, out *ECSTaskProperties, s conversion.Scope) error {
	return autoConvert_ecskube_ECSTaskProperties_To_v1alpha1_ECSTaskProperties(in, out, s)
}

func autoConvert_v1alpha1_ECSULimit_To_ecskube_ECSULimit(in *ECSULimit, out *ecskube.ECSULimit, s conversion.Scope) error {
	out.HardLimit = in.HardLimit
	out.Name = in.Name
	out.SoftLimit = in.SoftLimit
	return nil
}

// Convert_v1alpha1_ECSULimit_To_ecskube_ECSULimit is an autogenerated conversion function.
func Convert_v1alpha1_ECSULimit_To_ecskube_ECSULimit(in *ECSULimit, out *ecskube.ECSULimit, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSULimit_To_ecskube_ECSULimit(in, out, s)
}

func autoConvert_ecskube_ECSULimit_To_v1alpha1_ECSULimit(in *ecskube.ECSULimit, out *ECSULimit, s conversion.Scope) error {
	out.HardLimit = in.HardLimit
	out.Name = in.Name
	out.SoftLimit = in.SoftLimit
	return nil
}

// Convert_ecskube_ECSULimit_To_v1alpha1_ECSULimit is an autogenerated conversion function.
func Convert_ecskube_ECSULimit_To_v1alpha1_ECSULimit(in *ecskube.ECSULimit, out *ECSULimit, s conversion.Scope) error {
	return autoConvert_ecskube_ECSULimit_To_v1alpha1_ECSULimit(in, out, s)
}

func autoConvert_v1alpha1_ECSVolumeFrom_To_ecskube_ECSVolumeFrom(in *ECSVolumeFrom, out *ecskube.ECSVolumeFrom, s conversion.Scope) error {
	out.SourceContainer = in.SourceContainer
	out.ReadOnly = in.ReadOnly
	return nil
}

// Convert_v1alpha1_ECSVolumeFrom_To_ecskube_ECSVolumeFrom is an autogenerated conversion function.
func Convert_v1alpha1_ECSVolumeFrom_To_ecskube_ECSVolumeFrom(in *ECSVolumeFrom, out *ecskube.ECSVolumeFrom, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSVolumeFrom_To_ecskube_ECSVolumeFrom(in, out, s)
}

func autoConvert_ecskube_ECSVolumeFrom_To_v1alpha1_ECSVolumeFrom(in *ecskube.ECSVolumeFrom, out *ECSVolumeFrom, s conversion.Scope) error {
	out.SourceContainer = in.SourceContainer
	out.ReadOnly = in.ReadOnly
	return nil
}

// Convert_ecskube_ECSVolumeFrom_To_v1alpha1_ECSVolumeFrom is an autogenerated conversion function.
func Convert_ecskube_ECSVolumeFrom_To_v1alpha1_ECSVolumeFrom(in *ecskube.ECSVolumeFrom, out *ECSVolumeFrom, s conversion.Scope) error {
	return autoConvert_ecskube_ECSVolumeFrom_To_v1alpha1_ECSVolumeFrom(in, out, s)
}

func autoConvert_v1alpha1_ECSVolumeHost_To_ecskube_ECSVolumeHost(in *ECSVolumeHost, out *ecskube.ECSVolumeHost, s conversion.Scope) error {
	out.SourcePath = in.SourcePath
	return nil
}

// Convert_v1alpha1_ECSVolumeHost_To_ecskube_ECSVolumeHost is an autogenerated conversion function.
func Convert_v1alpha1_ECSVolumeHost_To_ecskube_ECSVolumeHost(in *ECSVolumeHost, out *ecskube.ECSVolumeHost, s conversion.Scope) error {
	return autoConvert_v1alpha1_ECSVolumeHost_To_ecskube_ECSVolumeHost(in, out, s)
}

func autoConvert_ecskube_ECSVolumeHost_To_v1alpha1_ECSVolumeHost(in *ecskube.ECSVolumeHost, out *ECSVolumeHost, s conversion.Scope) error {
	out.SourcePath = in.SourcePath
	return nil
}

// Convert_ecskube_ECSVolumeHost_To_v1alpha1_ECSVolumeHost is an autogenerated conversion function.
func Convert_ecskube_ECSVolumeHost_To_v1alpha1_ECSVolumeHost(in *ecskube.ECSVolumeHost, out *ECSVolumeHost, s conversion.Scope) error {
	return autoConvert_ecskube_ECSVolumeHost_To_v1alpha1_ECSVolumeHost(in, out, s)
}
